#Base image
FROM mysql

#Updating the image
RUN apt-get -y update && apt-get upgrade

#Adding bookstore's mysql files
ADD bookstore.sql /home/bookstore/bookstore.sql
ADD data.sql /home/bookstore/data.sql
ADD initdb.sh /home/bookstore/initdb.sh
RUN chmod 644 /home/bookstore/bookstore.sql
RUN chmod 644 /home/bookstore/data.sql
RUN chmod 755 /home/bookstore/initdb.sh